### ISSUE TITLE
Beta site not updated for 8.33kHz.

### ISSUE THREAD

**Issue by judemille** [lennycolton/vatglasses-data#128]
It would appear that beta.vatglasses.uk has not received the data update for 8.33 kHz in UK, NL, and DE. Since station recognition is done by frequency, this breaks the site.

**Comment by lennycolton** [comment]
The beta site exists for vACCs to test data and layout changes. 8.33kHz is not the only thing wrong or missing in the beta database - please don't rely on it to be correct!

The current 8.33kHz implementation is correctly displayed on the live site - https://vatglasses.uk.
