### ISSUE TITLE
Map infinitely draggable ISO loop

### ISSUE THREAD

**Issue by rffuret** [lennycolton/vatglasses-data#130]
Seems like if you drag the map in the east-west direction (or other way around), it just keeps on going instead of closing up the globe

![image](https://github.com/lennycolton/vatglasses-data/assets/29098568/ce3abe09-64e4-4514-96e8-c78a21324990)

**Comment by lennycolton** [comment]
This is a limitation of the mapping library. The most I can do is have it awkwardly jump when you go too far east/west, which gives a worse experience than just letting it scroll forever.
