### ISSUE TITLE
Airport Callsigns

### ISSUE THREAD

**Issue by lennycolton** [lennycolton/vatglasses-data#137]
![image](https://github.com/lennycolton/vatglasses-data/assets/40361891/e42c1d1b-e236-48c6-afa9-9c83d1973f90)

Is this the callsign for the controller? Looks like the airport default callsigns might still have some of the incorrect VATSpy callsigns.

**Comment by jivebiscuit** [comment]
Everything at MSY goes by just "New Orleans" so yeah, might be. Is this something I need to fix on our data or is it elsewhere?

**Comment by jivebiscuit** [comment]
Now I'm second guessing what you were referring to: airport name or the controller ID MSY_GND?

**Comment by lennycolton** [comment]
Yes - I do mean the airport name. Airport names are defined in your data file and should correspond to the airport's RTF callsign, rather than its "official" name.

**Comment by jivebiscuit** [comment]
Understood. I'll make the changes in test-data (will need to do that for all my defined airports) and to the PR into master later. Thanks!
