### ISSUE TITLE
[NEW] VATSEA Vietnam-Cambodia-Laos

### ISSUE THREAD

**Issue by amosngSP** [lennycolton/vatglasses-data#139]
Good Day,

VCL would like to on-board our sectors onto VATglasses, where the priority would be for VVHM, where effective next AIRAC we will be looking to revise our sectors to match the real life sectors, as it includes vertical splits.

I'll be happy to help implement this where needed, please do advise if you are happy to include this into vatglasses. Thanks!

**Comment by lennycolton** [comment]
Hello! I've invited you to both of our data repositiories.

[vatglasses-test-data](https://github.com/lennycolton/vatglasses-test-data) powers the [beta site](https://beta.vatglasses.uk). You should upload your data file here whilst it's in development. Any changes you make will be deployed immediately.

[vatglasses-data](https://github.com/lennycolton/vatglasses-data) (this repository) powers the [main site](https://vatglasses.uk). Once your file is ready for release, we'll add it here. This repo also has a [wiki](https://github.com/lennycolton/vatglasses-data/wiki) with details of the file format.

If you have EuroScope .ese files, we have a [parser](https://github.com/MatisseBE/vatglasses-converter) which will do 80% of the work for you. You'll have to add top-down airport ownership yourself but most sector data can be transferred directly.

I'm not familiar with VCL vACC, so feel free to combine all FIRs into one file or divide by FIR/country as appropriate.

**Comment by amosngSP** [comment]
Neat! Thanks a lot Lenny! I'll take a look in the coming weeks :)

**Comment by lennycolton** [comment]
Hi Amos, what's the current status of this?

**Comment by amosngSP** [comment]
Hey Lenny, apologise. It will probably require some work as the sectors we create in gng are probably not the right way to display in VATglasses. Will have to re-work it.

**Comment by lennycolton** [comment]
From a glance at the beta site, it looks like it's all displayed relatively well. Is there a specific issue you've noticed?

**Comment by amosngSP** [comment]
Hi Lenny,

I'm slightly OCD but basically because I made my sectors like how GNG wants it, you get weird circles over APP or TWR areas that are the same as ACC areas. I'd like to fix it up before I go further haha.

Also there are some changes to the airspace in Cambodia, so there'll be more changes before I proceed on.

Thanks for checking in!

**Comment by amosngSP** [comment]
I apologise I haven't been tardy with this lately. It's on our progress tracking list for now, hope I get to it soon!
