### ISSUE TITLE
EHEH_APP color

### ISSUE THREAD

**Issue by MatisseBE** [lennycolton/vatglasses-data#153]
![image](https://github.com/lennycolton/vatglasses-data/assets/51272243/f0234862-eca8-4d6f-a944-7d95c4d40bf5)
 Is this acceptable brightness? It's on the edge for me

**Comment by lennycolton** [comment]
@thijsschepman

**Comment by thijsschepman** [comment]
I agree with Matisse, it should be a lovely bright green now. See: #162
