### ISSUE TITLE
Yorkshire and Borders CTA not shown below FL 125

### ISSUE THREAD

**Issue by grahamdrabble** [lennycolton/vatglasses-data#19]
Hi,

Was flying a route today below the Yorkshire CTA (IPNOX in the south, DCS - INPIP in north).

VatGlasses is showing Scotting controlling above FL125 but that noone owns below FL125. It appears as though Yorkshire CTA 16 and Broders CTA 8 are missing from the data which cover FL95-FL125

Can't work out what needs to change in data so unfortunately you're just going to get the issue and not a PR

Graham

**Comment by lennycolton** [comment]
Hi Graham,

Yorkshire CTA 16 and Borders CTA 8 are only active from 20:00-07:00 local. Could you please confirm whether they appear between these times?

**Comment by grahamdrabble** [comment]
Just checked and no, not shown. Cool you're even attempting to do the time based stuff though

**Comment by lennycolton** [comment]
Bug in code for all FUA active across midnight, now fixed.
