### ISSUE TITLE
[DE] AFIS towers do not show up in map 

### ISSUE THREAD

**Issue by StefanL01** [lennycolton/vatglasses-data#200]
Hi
In the map a german AFIS tower (e.g. EDQD_I_TWR) does not show up. It shows up in the "online atc"list however, but the "callsign" is marked "unknown".
I would be nice if the AFIS show up as some might choose their spontanous flight with a quick look in the map for suitable routes and distances
@jannikvogel I was asked to tag you for this issue

Thx
Stefan

**Comment by jannikvogel** [comment]
It would be necessary to add all existing airports with an ICAO code. We are giving it a thought to add all airports with IFR procedures, but adding every existing airport with ICAO code manually would definitely be excessive.

**Comment by lennycolton** [comment]
> It would be necessary to add all existing airports with an ICAO code. We are giving it a thought to add all airports with IFR procedures, but adding every existing airport with ICAO code manually would definitely be excessive.

Could you get them from your sector file or the data you use to feed VATSpy? Most countries include all of their published airports but most of those don't have any top-down attached so only appear when the relevant TWR/AFIS/AG unit opens.

**Comment by MatisseBE** [comment]
the vatspy method is automated with my script
