### ISSUE TITLE
[UK] Temporary Reserved Areas

### ISSUE THREAD

**Issue by lennycolton** [lennycolton/vatglasses-data#22]
Add UK TRAs (excluding TRA(G)s), active at their published times. Where summer and winter active times (in UK local time) differ, select the longer one.

**Comment by MatisseBE** [comment]
Use https://eaup.vatsim.pt/api/docs for activation times. Data source is Eurocontrol NM. And for notams FAA.

**Comment by lennycolton** [comment]
Does this display all scheduled activations or is it just the NOTAMed ones?

**Comment by MatisseBE** [comment]
There's two different sources. The usual NOTAMS, and those sourced from ANSPs that EUROCONTROL publishes. Those EC ones come from EAUP/UUP.

You can find it at https://www.public.nm.eurocontrol.int/PUBPORTAL/gateway/spec/ - under European AUP/UUP

Additionally, also the levels are dynamic.

**Comment by lennycolton** [comment]
Feature postponed indefinitely
