### ISSUE TITLE
Basic Data conflicting with Established ARTCCs?

### ISSUE THREAD

**Issue by jivebiscuit** [lennycolton/vatglasses-data#221]
Hello, with the addition of the basic US ARTCC boundaries it seems like ZHU and ZAB enroute sectors aren't being displayed on live or beta. Anything we need to do on our end?

**Comment by lennycolton** [comment]
ZAB and ZHU are both still there. I've altered the main site so that boundaries only show if the relevant unit is online. You can still view all sector boundaries at https://vatglasses.uk/all.

**Comment by lennycolton** [comment]
ZAB and ZHU are both still there. I've altered the main site so that boundaries only show if the relevant unit is online. You can still view all sector boundaries at https://vatglasses.uk/all.

**Comment by jivebiscuit** [comment]
Cheers thanks!
