### ISSUE TITLE
[GER] Sector Colours

### ISSUE THREAD

**Issue by DefinitelyBogan** [lennycolton/vatglasses-data#24]
EDGG_KTG_CTR is currently online however does not show clearly on the map [Image](https://cdn.discordapp.com/attachments/816737596272410634/1056971212649152522/image.png)

**Comment by lennycolton** [comment]
@jannikvogel Can you take a look at this, please?

**Comment by jannikvogel** [comment]
KTG currently has a very dark color due to randomly created hex color codes. Will fix

**Comment by MatisseBE** [comment]
There have also been instances where the colours of neighbouring sectors are almost identical. Is this something that can be avoided? Ill post screenshots if I see them happen again.

**Comment by MatisseBE** [comment]
![image](https://user-images.githubusercontent.com/51272243/210639163-24c01d11-efb7-490a-b9c4-cac6c7c53a46.png)
![image](https://user-images.githubusercontent.com/51272243/210639166-a535b27a-ecd1-4d5f-b0fb-50a877541bed.png)

**Comment by MatisseBE** [comment]
![image](https://user-images.githubusercontent.com/51272243/211902915-a9f73dde-60fa-49f4-949e-4e3e8362453f.png)
Same goes for this sector.

**Comment by lennycolton** [comment]
Thanks for these @MatisseBE. I'm sure Team Germany will find them to be a great help.

**Comment by jannikvogel** [comment]
Jup, will do this after my exams in the next weeks. If anyone else feels motivated to do this, you are invited to draft a pull request ;)

**Comment by DefinitelyBogan** [comment]
Hi, this seems to be a issue again for KTG

![image](https://user-images.githubusercontent.com/11663187/219878425-1d862014-47f4-4d47-805d-0f4eb6700751.png)

**Comment by lennycolton** [comment]
Any progress on this?

**Comment by PaulaBras** [comment]
Is everything okay? Can it be closed then?

**Comment by jannikvogel** [comment]
All fine from my side. Danke, Paul :)

**Comment by MatisseBE** [comment]
> ![image](https://user-images.githubusercontent.com/51272243/210639163-24c01d11-efb7-490a-b9c4-cac6c7c53a46.png) ![image](https://user-images.githubusercontent.com/51272243/210639166-a535b27a-ecd1-4d5f-b0fb-50a877541bed.png)

@jannikvogel GIN and PAH still have the same color.
