### ISSUE TITLE
[FR] LFBB_CTR Not on VATGLASS

### ISSUE THREAD

**Issue by Iwhite67** [lennycolton/vatglasses-data#245]
![image](https://github.com/lennycolton/vatglasses-data/assets/9698964/3c58743d-144e-4102-92a1-b965c93e8080)
![image](https://github.com/lennycolton/vatglasses-data/assets/9698964/81eb8b65-1448-4d0a-8895-7bfb05b22de5)
![image](https://github.com/lennycolton/vatglasses-data/assets/9698964/1792a71b-cada-4d5b-b38d-fd26cab1bf91)

Hello, all the screenshots were taken this evening, LFBB_CTR is connected but not visible in the list of connected controllers on vatglass

**Comment by lennycolton** [comment]
That's odd. I just checked and it's visible. Was this within a minute or two after they logged on?
![image](https://github.com/lennycolton/vatglasses-data/assets/40361891/ff9958e3-3a63-4163-92e3-c833623371bd)
