### ISSUE TITLE
ZAN Data Issues

### ISSUE THREAD

**Issue by dhawton** [lennycolton/vatglasses-data#247]
There are a good number of errors in the ZAN data. Please add a warning that that data is likely inaccurate or incorrect so that pilots don't rely on it as a source of truth. You can reach me at daniel[at]zanartcc.org if you have any questions. Thank you.

**Comment by lennycolton** [comment]
Hello! I built the ZAN data set from information sent by an individual claiming to be the ZAN FE. It looks like you don't actually have one so my bad for not checking the credential. Have you considered making a PR with corrections?

**Comment by dhawton** [comment]
I do not have the time.

**Comment by lennycolton** [comment]
ZAN data to be removed.
