### ISSUE TITLE
vACC Romania

### ISSUE THREAD

**Issue by tgpetrica** [lennycolton/vatglasses-data#25]
Hello,

I am Teodor Petrica, [PR of VATSIM ROMANIA](https://rovacc.ro/staff-team/) (LRBB FIR and LUUU FIR) and we would like to be part of this project,

Contact me via mail at teodor.petrica@rovacc.ro and advise if your need further information. 

Thank you,
Teodor Petrica
ACCRO7, VATSIM ROMANIA

**Comment by lennycolton** [comment]
I've sent you a DM on Discord.
