### ISSUE TITLE
Usage of VatGlasses data

### ISSUE THREAD

**Issue by daniluk4000** [lennycolton/vatglasses-data#257]
Hello there. I'm currently developing https://vatsim-radar.com. Me and my first users believe that great VatGlasses data is vital for making a perfect service - so I would like to use that :)

Despite your data being Open Source, you asked for a written permission to be granted first before anybody uses your data - so here I am, asking for that. 

1. I will include this VatGlasses repo in attributions in same way as SimAware does
2. Project will also go open source (but later)
3. Users will not have to pay or smth like that to access data

Add or ask anything to that - I'll be happy to answer. 

With hope to use your data, Daniel.

**Comment by lennycolton** [comment]
Resolved via Discord
