### ISSUE TITLE
[Germany] Upper Airspace in EDUU North configured incorrect

### ISSUE THREAD

**Issue by lucianoasmus** [lennycolton/vatglasses-data#27]
Currently the Ostsee and Havel sectors ("id": "Ostsee" and "id": "Havel") are configured incorrectly, not shown as active when Müritz (MRZ, 124.175) is online. 

MRZ does cover these two sectors "bottom up". It would be really cool if that could be corrected, since it is one of our main sectors overhead Berlin and staffed pretty often.

**Comment by lennycolton** [comment]
@jannikvogel
