### ISSUE TITLE
LOVV Airspace

### ISSUE THREAD

**Issue by seelenkrieger** [lennycolton/vatglasses-data#29]
Hello,

I am Patrick Weineis, Sectorfile manager of VACC Austria (see https://gng.aero-nav.com/LOVV/admin_participating_vacc) and we would like try your project,

you could contact me either at patrick.weineis@outlook.com or via discord Patrick Weineis#2923

Thank you,
Patrick Weineis

**Comment by lennycolton** [comment]
I've sent you a DM on Discord.
