### ISSUE TITLE
Mapdata valid key error

### ISSUE THREAD

**Issue by nubbix** [lennycolton/vatglasses-data#34]
Think you need to update your license key

**Comment by nubbix** [comment]
![Uploading 2023-01-19_135237.jpg…]()

**Comment by lennycolton** [comment]
Sorry about this - I forgot to set up a whitelist for who could use the API key. Somebody took advantage to the tune of 90,000 requests.

I've restored mapping functionality.

**Comment by nubbix** [comment]
Excellent, thanks
