### ISSUE TITLE
Wrong freq Brussels control

### ISSUE THREAD

**Issue by MatisseBE** [lennycolton/vatglasses-data#36]
While trying to figure out why only Brussels Control East was showing as online on vatglasses, I found out that the frequency for West is incorrect: 131.000 instead of **131.100**. I assume this is also the cause for my issue?
![image](https://user-images.githubusercontent.com/51272243/213776520-4c981dbf-044c-4733-aad9-ef67aef7f4bc.png)
![image](https://user-images.githubusercontent.com/51272243/213776523-afb4ee68-4c58-4d6e-b4b1-d8ac9e7c20d1.png)
![image](https://user-images.githubusercontent.com/51272243/213776528-300e4666-5209-4804-8d38-62c24bba3981.png)

**Comment by lennycolton** [comment]
Trust it to be the one that I should know - fixed
