### ISSUE TITLE
Eurocenter sectors

### ISSUE THREAD

**Issue by MatisseBE** [lennycolton/vatglasses-data#46]
Since an EUC sector is only relevant in neighbouring sectors, they are likely not present in the ESE for that particular vACC in their own sectors. I assume this oversight causes those EUC sectors to not be present on vatglasses either.

(Here EURM-E covers parts of Germany and (sometimes) Pahra too)

![image](https://user-images.githubusercontent.com/51272243/222923222-647865d9-afb9-4abf-875b-3aa51c72a85f.png)
![image](https://user-images.githubusercontent.com/51272243/222917140-38dd55aa-85cd-428a-aadc-127ac62cc65e.png)

**Comment by lennycolton** [comment]
I added EURM-W, EURM-E, and EURE a while back but I assume that local updates removed them. This is one of those things which will have to be handled by each individual vACC when they push updates.
