### ISSUE TITLE
Disturbing Map

### ISSUE THREAD

**Issue by nubbix** [lennycolton/vatglasses-data#55]
Why on earth did you implement this ugly ass Map. Please let me know how to change back?

![2023-04-01_234619](https://user-images.githubusercontent.com/6438354/229315535-d55ca3ab-1d13-4292-99f3-329daf32816a.jpg)

**Comment by lennycolton** [comment]
It's an April Fools joke. It will change back at midnight.

**Comment by nubbix** [comment]
> It's an April Fools joke. It will change back at midnight.

Well that work lmao.. Got so affraid I immediately got an disturbence on the heart monitor.
