### ISSUE TITLE
ATC Data API Usage request

### ISSUE THREAD

**Issue by knidarkness** [lennycolton/vatglasses-data#70]
Hello,

I am building a tool [fsplan.net](https://fsplan.net) ([repo](https://github.com/knidarkness/fsplan.net)) and want to add a new filter to look for destinations with active Vatsim coverage either top-down or "in the vicinity". 

For a long time I have been using [vatglasses.uk](https://www.vatglasses.uk/) and recently I found that you have a country/region/airport data for online VATSIM ATC essentially.  Now, the question is, is it acceptable to make API call to your service to get this type of data or, alternatively, could you point me in the right direction as to where this kind of data can be gathered/assembled?

Thanks,
Serhii.

**Comment by lennycolton** [comment]
Hi Serhii,

If you're looking for data about which ATC is online on VATSIM, the best place to start is http://status.vatsim.net, which lists the various feeds. If you're looking for the VATGlasses sector API, I'm afraid that's not open for use by other projects.

**Comment by knidarkness** [comment]
Hi @lennycolton, and thanks for your reply. I was speaking not (mainly) about the API but also about the contents of this repo, as while it's public, it has no OSS license -> considered proprietary (see [link](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license)). Does your comment also explicitly prohibit using the data (sector jsons) available in this GitHub repo? If so, while it's sad, nonetheless, thank you for clarification and reply.
