### ISSUE TITLE
EURW-S Ownership

### ISSUE THREAD

**Issue by MatisseBE** [lennycolton/vatglasses-data#75]
![image](https://github.com/lennycolton/vatglasses-test-data/assets/51272243/7dc79639-4f5f-4778-8388-9ec89ad235dd)
![image](https://github.com/lennycolton/vatglasses-test-data/assets/51272243/3a00b985-2e1d-4ffb-af56-d3d7a4329870)

Some of the EURW-S sectors go as low as 1000ft
And some don't start until FL340

**Comment by lennycolton** [comment]
Looks like local sectorisation has had EURW-S ownership added as a "best fit" without applying any unnatural divisions. I know they've done this for EURW-N, but that varies the base between FL245-295, depending on the FIR. Random variation between 1000ft and FL340 feels like a bug.

**Comment by lennycolton** [comment]
And what's going on with Portugal?

**Comment by lennycolton** [comment]
What should the Portugal ownership look like? @becas22

**Comment by becas22** [comment]
> What should the Portugal ownership look like? @becas22

All the FIR should be lit above FL245.
The sectors being North, Centre, South, Demos, Veram and Madeira

**Comment by lennycolton** [comment]
> > What should the Portugal ownership look like? @becas22
> 
> All the FIR should be lit above FL245. The sectors being North, Centre, South, Demos, Veram and Madeira

I've taken a look and this was implemented correctly, but with an incorrect position reference. Fixed in the PR.

**Comment by lennycolton** [comment]
@rpuig2001 What should your EURW split look like?
