### ISSUE TITLE
Maghreb

### ISSUE THREAD

**Issue by lennycolton** [lennycolton/vatglasses-data#87]
Add Maghreb vACC - Morocco, ~~Algeria~~, and Tunisia. @lennycolton to review.

**Comment by lennycolton** [comment]
Local staff implementing changes as required to fit their sector file into the repository.

**Comment by cBobbie** [comment]
Should have this completed very shortly, just fixing up the colours for Tunisia & Morocco then I think it'll be ready to be pushed to the main site. (Algeria will come to Vatglasses once we finish the ES version of Algeria)

I will write here again once I've finished with the colours.

**Comment by lennycolton** [comment]
How's this coming along?

**Comment by cBobbie** [comment]
Hi Lenny, yeah sorry about the wait. It's pretty much there but as mentioned, just needs colours but I'll see if I can get it done by today. Will let you know.

Also just so you know, we decided not to create Algeria in ES, and just keep it in Vatsys. So will be happy to hear if you have any methods on using vatsys data to convert over to Vatglasses.

Cheers.

**Comment by cBobbie** [comment]
Working on it as we speak. Should have Morocco ready in under an hour.
Tunisia is complete.

**Comment by cBobbie** [comment]
Morocco is complete. @lennycolton When you are able to, can you please check both tunisia & morocco to see if they are 'correct' for you?
If so, feel free to submit them. I may change the colours for the sectors like GMAC_ON, GMMM_E, etc in the future, but for now, I'm just leaving them as the same colour.
